services:
  # Production application service
  language-learning-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: language-learning-app-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-deepseek.r1-v1:0}
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - app_uploads:/app/backend/uploads
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "node", "backend/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Nginx reverse proxy with HTTPS support
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - language-learning-app
    networks:
      - app_network

volumes:
  app_uploads:
    driver: local

networks:
  app_network:
    driver: bridge